/**
 * Manual mapping of KNOT names to panorama image URLs.
 * Add your panorama image URLs here for each story KNOT.
 */
export const imageMapping: { [knotName: string]: string } = {
  "0": "/scene-1.png",
  "Scene_1_Battle": "https://res.cloudinary.com/dmq8ipket/image/upload/v1764710176/Scene_1_Battle_avhena.png",
  "Scene_1_Battle_b": "https://res.cloudinary.com/dmq8ipket/image/upload/v1764710175/Scene_1_Battle_b_etggeo.png",
  "Scene_1_Battle_bb": "https://res.cloudinary.com/dmq8ipket/image/upload/v1764710178/Scene_1_Battle_bb_jhpxjd.png",
  "Scene_2_Inspection": "https://res.cloudinary.com/dmq8ipket/image/upload/v1764710177/Scene_2_Inspection_fd2tp0.png",
  "Scene_2b_Order_to_Retreat": "/scene-1.png",
  "Scene_2b_Order_to_Retreat_b": "/scene-1.png",
  "Scene_2c_Camp_Doodle": "/scene-1.png",
  "Scene_2c_Camp_Doodle_e": "/scene-1.png",
  "Scene_2c_Camp_Doodle_ea": "/scene-1.png",
  "Scene_2c_Camp_Doodle_a": "/scene-1.png",
  "Scene_2c_White_Army": "/scene-1.png",
  "Scene_2c_Camp_Doodle_b": "/scene-1.png",
  "Scene_2c_Camp_Doodle_c": "/scene-1.png",
  "Scene_2c_Camp_Doodle_d": "/scene-1.png",
  "Scene_2_learn": "/scene-1.png",
  "Scene_3_Truck_Refugees": "/scene-1.png",
  "Scene_3_Truck_Refugees_a": "/scene-1.png",
  "Scene_3_Truck_Refugees_b": "/scene-1.png",
  "Scene_4_Ambush": "/scene-1.png",
  "Scene_4_Ambush_a": "/scene-1.png",
  "Scene_5_Switch_Roles": "/scene-1.png",
  "Scene_5_Switch_Roles_b": "/scene-1.png",
  "Scene_5b_The_Letter": "/scene-1.png",
  "Scene_6_Graves_Tallinn": "/scene-1.png",
  "Scene_6_Graves_Tallinn_a": "/scene-1.png",
  "Scene_6_Gulag": "/scene-1.png",
  "Scene_6_Graves_Tallinn_b": "/scene-1.png",
  "Scene_6_Graves_Tallinn_c": "/scene-1.png",
  "Scene_6_Graves_Tallinn_d": "/scene-1.png",
  "Scene6_Kapten_Evald_Viires": "/scene-1.png",
  "Scene_6_Tallinn": "/scene-1.png",
  "Scene_7_Aino": "/scene-1.png",
  "Scene_7_Aino_b": "/scene-1.png",
  "Scene_7_Aino_ba": "/scene-1.png",
  "Scene_7_Aino_bb": "/scene-1.png",
  "Scene_7_Aino_bc": "/scene-1.png",
  "Scene_8_Viires_Threat": "/scene-1.png",
  "Viires_Reaction": "/scene-1.png",
  "Scene_9_Saaremaa_Home": "/scene-1.png",
  "Scene_9_Saaremaa_Home_a": "/scene-1.png",
  "Scene_9_Saaremaa_Home_b": "/scene-1.png",
  "Scene_9_Saaremaa_Home_c": "/scene-1.png",
  "Scene_10_The_Stream": "/scene-1.png",
  "Scene_10_The_Stream_refuse": "/scene-1.png",
  "Ending_Scene": "/scene-1.png",
  "Conclusion": "/scene-1.png",
  "default": "/scene-1.png",
};

